# Generated by Django 4.1.7 on 2023-06-18 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatrimonialProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("short_bio", models.TextField(blank=True)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=255
                    ),
                ),
                ("height", models.CharField(blank=True, max_length=255)),
                (
                    "country",
                    django_countries.fields.CountryField(max_length=2, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255)),
                ("caste", models.CharField(blank=True, max_length=255)),
                ("birthday", models.DateField(blank=True)),
                ("education", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=255, null=True)),
                ("profession", models.CharField(blank=True, max_length=255)),
                ("income", models.PositiveIntegerField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrimonial_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Matrimonial Profiles",
            },
        ),
        migrations.CreateModel(
            name="MatrimonialProfileImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_image",
                    models.ImageField(null=True, upload_to="matrimonial_images/"),
                ),
                (
                    "matrimonial_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="matrimonials.matrimonialprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
