# Generated by Django 4.1.7 on 2023-06-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matrimonialprofile",
            name="caste",
        ),
        migrations.RemoveField(
            model_name="matrimonialprofile",
            name="language",
        ),
        migrations.AddField(
            model_name="matrimonialprofile",
            name="religion",
            field=models.CharField(
                choices=[
                    ("C", "Christian"),
                    ("M", "Muslim"),
                    ("H", "Hindu"),
                    ("S", "Sikh"),
                    ("B", "Buddhism"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="education",
            field=models.CharField(
                choices=[
                    ("UG", "Under Graduation"),
                    ("G", "Graduation"),
                    ("PG", "Post Graduation"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
