# Generated by Django 4.1.7 on 2023-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0004_conversation_alter_connectionrequest_receiver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionrequest",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Accepted"), ("R", "Rejected")],
                default="P",
                max_length=1,
            ),
        ),
    ]
