# Generated by Django 4.1.7 on 2023-06-22 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matrimonials", "0005_alter_connectionrequest_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matrimonialprofileimage",
            old_name="_image",
            new_name="image",
        ),
    ]
