# Generated by Django 4.1.7 on 2023-06-12 15:53

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="short_bio",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="education",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="height",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="income",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profession",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="religion",
        ),
        migrations.AlterField(
            model_name="profile",
            name="_avatar",
            field=models.ImageField(
                help_text="The avatar image of the user.", upload_to="customer_image/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="MatrimonialProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_avatar",
                    models.ImageField(upload_to="customer_matrimonial_profile/"),
                ),
                ("short_bio", models.TextField(blank=True)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=255
                    ),
                ),
                ("height", models.CharField(blank=True, max_length=255)),
                (
                    "country",
                    django_countries.fields.CountryField(max_length=2, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255)),
                ("caste", models.CharField(blank=True, max_length=255)),
                ("birthday", models.DateField(blank=True)),
                ("education", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="The phone number of the user.",
                        max_length=20,
                        validators=[core.validators.validate_phone_number],
                    ),
                ),
                ("profession", models.CharField(blank=True, max_length=255)),
                ("income", models.PositiveIntegerField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrimonial_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Matrimonial Profiles",
            },
        ),
    ]
