# Generated by Django 4.1.7 on 2023-06-18 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_matrimonialprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MatrimonialProfile",
        ),
    ]
