# Generated by Django 4.1.7 on 2023-06-22 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_delete_matrimonialprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="_avatar",
            new_name="avatar",
        ),
    ]
