# Generated by Django 4.1.7 on 2023-06-12 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdImages",
            new_name="AdImage",
        ),
        migrations.AddField(
            model_name="ad",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to="ads.adcategory",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="condition",
            field=models.CharField(
                blank=True, choices=[("N", "New"), ("U", "Used")], max_length=1
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ad",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to="ads.adsubcategory",
            ),
        ),
        migrations.AlterField(
            model_name="adsubcategory",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="ads.adcategory",
            ),
        ),
        migrations.CreateModel(
            name="FavouriteAd",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "ad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_ads",
                        to="ads.ad",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
