# Generated by Django 4.1.7 on 2023-06-14 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_ad_ad_creator_favouritead_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adcategory",
            options={"verbose_name_plural": "Ad Categories"},
        ),
        migrations.AlterModelOptions(
            name="adsubcategory",
            options={"verbose_name_plural": "Ad SubCategories"},
        ),
    ]
