# Generated by Django 4.1.7 on 2023-06-18 00:30

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0005_alter_ad_sub_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="date_and_time",
        ),
        migrations.AlterField(
            model_name="ad",
            name="location",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
