# Generated by Django 4.1.7 on 2023-06-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0006_remove_ad_condition_remove_ad_date_and_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
