# Generated by Django 4.1.7 on 2023-06-20 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0007_ad_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="sub_category",
        ),
    ]
