# Generated by Django 4.1.7 on 2023-06-22 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0008_remove_ad_sub_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adcategory",
            old_name="_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="adimage",
            old_name="_image",
            new_name="image",
        ),
    ]
