# Generated by Django 4.1.7 on 2023-06-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0009_rename__image_adcategory_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="status",
            field=models.CharField(
                choices=[
                    ("PA", "Paused"),
                    ("D", "Denied"),
                    ("P", "Pending"),
                    ("A", "Active"),
                ],
                default="P",
                max_length=2,
                null=True,
            ),
        ),
    ]
