# Generated by Django 4.1.7 on 2023-06-25 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0010_ad_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="is_active",
            new_name="is_approved",
        ),
    ]
