# Generated by Django 4.1.7 on 2023-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0013_alter_adimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adimage",
            name="image",
            field=models.ImageField(
                default=None,
                help_text="The image of a particular ad.",
                upload_to="ad_images/",
            ),
        ),
    ]
