# Generated by Django 4.1.7 on 2023-07-10 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0016_alter_adcategory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcategory",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="category_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "svg"]
                    )
                ],
            ),
        ),
    ]
