RELIGION_CHRISTIAN = "C"
RELIGION_MUSLIM = "M"
RELIGION_HINDU = "H"
RELIGION_SIKH = "S"
RELIGION_BUDDHISM = "B"

RELIGION_CHOICES = (
    (RELIGION_CHRISTIAN, "Christian"),
    (RELIGION_MUSLIM, "Muslim"),
    (RELIGION_HINDU, "Hindu"),
    (RELIGION_SIKH, "Sikh"),
    (RELIGION_BUDDHISM, "Buddhism"),
)

EDUCATION_UNDER_GRADUATION = "UG"
EDUCATION_GRADUATION = "G"
EDUCATION_POST_GRADUATION = "PG"

EDUCATION_CHOICES = (
    (EDUCATION_UNDER_GRADUATION, "Under Graduation"),
    (EDUCATION_GRADUATION, "Graduation"),
    (EDUCATION_POST_GRADUATION, "Post Graduation"),
)

CONNECTION_PENDING = "P"
CONNECTION_ACCEPTED = "A"
CONNECTION_REJECTED = "R"

CONNECTION_CHOICES = (
    (CONNECTION_PENDING, "Pending"),
    (CONNECTION_ACCEPTED, "Accepted"),
    (CONNECTION_REJECTED, "Rejected"),
)