CONDITION_USED = "U"
CONDITION_NEW = "N"

CONDITION_CHOICES = (
    (CONDITION_NEW, "New"),
    (CONDITION_USED, "Used"),
)

PAYMENT_PENDING = "P"
PAYMENT_COMPLETE = "C"
PAYMENT_FAILED = "F"

PAYMENT_STATUS = (
    (PAYMENT_PENDING, "Pending"),
    (PAYMENT_COMPLETE, "Complete"),
    (PAYMENT_FAILED, "Failed"),
)
