CONDITION_USED = "U"
CONDITION_NEW = "N"

CONDITION_CHOICES = (
    (CONDITION_NEW, "New"),
    (CONDITION_USED, "Used"),
)

PAYMENT_PENDING = "P"
PAYMENT_COMPLETE = "C"
PAYMENT_FAILED = "F"

PAYMENT_STATUS = (
    (PAYMENT_PENDING, "Pending"),
    (PAYMENT_COMPLETE, "Complete"),
    (PAYMENT_FAILED, "Failed"),
)

STATUS_PENDING = "P"
STATUS_PAUSED = "PA"
STATUS_ACTIVE = "A"
STATUS_DENIED = "D"

STATUS_CHOICES = (
    (STATUS_PAUSED, "Paused"),
    (STATUS_DENIED, "Denied"),
    (STATUS_PENDING, "Pending"),
    (STATUS_ACTIVE, "Active"),
)